language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19
before_script:
  - python addServer.py
script:
  - mvn clean install --settings ~/.m2/settings.xml

