language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19
after_success:
  - python addServer.py
  - mvn clean install --settings ~/.m2/mySettings.xml

