language: android

env:
- BRANCH_NAME=$TRAVIS_BRANCH

android:
  components:
    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19
before_script:
  - python addServer.py
  - python modifyPom.py
script:
  - mvn clean install sonar:sonar --settings ~/.m2/settings.xml -Dsonar.host.url=http://sonar.miairline.com

